package com.quantfinlib.rates;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

/** Nelson-Siegel: exact recovery, flat-curve exactness, inversion sign. */
class NelsonSiegelTest {

    private static final double[] TENORS = {0.25, 0.5, 1, 2, 3, 5, 7, 10, 15, 20};

    @Test
    void recoversPlantedParametersFromExactData() {
        // Data generated by the model itself must fit almost perfectly
        // (lambda grid granularity is the only residual).
        NelsonSiegel.Fit planted = new NelsonSiegel.Fit(0.05, -0.02, 0.01, 2.0, 0);
        double[] rates = new double[TENORS.length];
        for (int i = 0; i < TENORS.length; i++) {
            rates[i] = planted.zeroRate(TENORS[i]);
        }
        NelsonSiegel.Fit fit = NelsonSiegel.fit(TENORS, rates);
        assertTrue(fit.rmse() < 1e-4, "rmse=" + fit.rmse());
        assertEquals(0.05, fit.b0(), 2e-3);
        assertEquals(0.03, fit.shortRate(), 2e-3); // b0 + b1
        for (int i = 0; i < TENORS.length; i++) {
            assertEquals(rates[i], fit.zeroRate(TENORS[i]), 2e-4);
        }
    }

    @Test
    void flatCurveFitsExactlyAtAnyLambda() {
        // A constant target is in the span of the constant regressor: OLS
        // hits it exactly, whatever lambda the grid picks.
        double[] rates = new double[TENORS.length];
        java.util.Arrays.fill(rates, 0.04);
        NelsonSiegel.Fit fit = NelsonSiegel.fit(TENORS, rates);
        assertEquals(0, fit.rmse(), 1e-12);
        assertEquals(0.04, fit.zeroRate(0.5), 1e-10);
        assertEquals(0.04, fit.zeroRate(30), 1e-10);
    }

    @Test
    void invertedCurveGetsPositiveSlopeParameter() {
        // Short rates above long rates: z(0) > z(inf) means b1 > 0 —
        // the recession-signal sign, fitted not forced.
        double[] rates = {0.055, 0.054, 0.052, 0.049, 0.046, 0.042, 0.040, 0.038, 0.037, 0.036};
        NelsonSiegel.Fit fit = NelsonSiegel.fit(TENORS, rates);
        assertTrue(fit.b1() > 0, "b1=" + fit.b1());
        assertTrue(fit.shortRate() > fit.longRate());
    }

    @Test
    void gatesRefuseDegenerateInput() {
        double[] ok = {0.01, 0.02, 0.03, 0.04};
        assertThrows(IllegalArgumentException.class,
                () -> NelsonSiegel.fit(new double[]{1, 2, 3}, new double[]{0.01, 0.02, 0.03}));
        assertThrows(IllegalArgumentException.class,
                () -> NelsonSiegel.fit(new double[]{0, 1, 2, 3}, ok));
        assertThrows(IllegalArgumentException.class,
                () -> NelsonSiegel.fit(new double[]{1, 2, 3, 4},
                        new double[]{0.01, Double.NaN, 0.03, 0.04}));
        NelsonSiegel.Fit fit = NelsonSiegel.fit(new double[]{1, 2, 3, 4}, ok);
        assertThrows(IllegalArgumentException.class, () -> fit.zeroRate(0));
        assertThrows(IllegalArgumentException.class, () -> fit.zeroRate(-1));
    }
}
