package com.quantfinlib.rates;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Svensson: planted-parameter recovery, exact NS nesting on b3 = 0 data,
 * and the raison d'etre — a two-hump curve plain Nelson-Siegel cannot bend
 * into, fitted head-to-head.
 */
class SvenssonTest {

    private static final double[] TENORS =
            {0.25, 0.5, 1, 2, 3, 5, 7, 10, 15, 20, 25, 30};

    @Test
    void recoversPlantedParametersFromExactData() {
        // Data generated by the model itself must fit almost perfectly
        // (the 2-D lambda grid granularity is the only residual).
        Svensson.Fit planted = new Svensson.Fit(0.045, -0.02, 0.03, -0.04, 1.5, 7.0, 0);
        double[] rates = new double[TENORS.length];
        for (int i = 0; i < TENORS.length; i++) {
            rates[i] = planted.zeroRate(TENORS[i]);
        }
        Svensson.Fit fit = Svensson.fit(TENORS, rates);
        assertTrue(fit.rmse() < 5e-5, "rmse=" + fit.rmse());
        assertEquals(0.045, fit.b0(), 5e-3);
        assertEquals(0.025, fit.shortRate(), 5e-3);   // b0 + b1
        assertEquals(0.045, fit.longRate(), 5e-3);
        assertTrue(fit.lambda2() > fit.lambda1(), "hump ordering enforced");
        for (int i = 0; i < TENORS.length; i++) {
            assertEquals(rates[i], fit.zeroRate(TENORS[i]), 2e-4);
        }
    }

    @Test
    void nestsNelsonSiegelOnSingleHumpData() {
        // Data from a pure NS curve (b3 = 0): Svensson contains NS, so the
        // fit must reproduce it essentially exactly — the extra hump earns
        // nothing but cannot hurt in-sample.
        NelsonSiegel.Fit ns = new NelsonSiegel.Fit(0.05, -0.02, 0.01, 2.0, 0);
        double[] rates = new double[TENORS.length];
        for (int i = 0; i < TENORS.length; i++) {
            rates[i] = ns.zeroRate(TENORS[i]);
        }
        Svensson.Fit sv = Svensson.fit(TENORS, rates);
        assertTrue(sv.rmse() < 2e-4, "rmse=" + sv.rmse());
        for (int i = 0; i < TENORS.length; i++) {
            assertEquals(rates[i], sv.zeroRate(TENORS[i]), 5e-4);
        }
        assertEquals(0.05, sv.longRate(), 5e-3);
        assertEquals(0.03, sv.shortRate(), 5e-3);
    }

    @Test
    void doubleHumpBeatsPlainNelsonSiegel() {
        // A short-end bump plus a long-end dip: one hump must split the
        // difference, two humps nail it — the whole point of the model.
        Svensson.Fit planted = new Svensson.Fit(0.04, -0.015, 0.05, -0.06, 0.8, 8.0, 0);
        double[] rates = new double[TENORS.length];
        for (int i = 0; i < TENORS.length; i++) {
            rates[i] = planted.zeroRate(TENORS[i]);
        }
        Svensson.Fit sv = Svensson.fit(TENORS, rates);
        NelsonSiegel.Fit ns = NelsonSiegel.fit(TENORS, rates);
        assertTrue(sv.rmse() < 1e-4, "Svensson rmse=" + sv.rmse());
        assertTrue(ns.rmse() > 5 * sv.rmse(),
                "NS rmse " + ns.rmse() + " should be far above Svensson " + sv.rmse());
    }

    @Test
    void gatesRefuseDegenerateInput() {
        double[] okT = {0.5, 1, 2, 3, 5, 10};
        double[] okR = {0.02, 0.025, 0.03, 0.032, 0.035, 0.037};
        assertThrows(IllegalArgumentException.class,     // < 6 observations
                () -> Svensson.fit(new double[]{1, 2, 3, 4, 5}, new double[]{1, 2, 3, 4, 5}));
        assertThrows(IllegalArgumentException.class,     // misaligned
                () -> Svensson.fit(okT, new double[]{0.02, 0.025, 0.03}));
        assertThrows(IllegalArgumentException.class,     // zero tenor
                () -> Svensson.fit(new double[]{0, 1, 2, 3, 5, 10}, okR));
        assertThrows(IllegalArgumentException.class,     // NaN rate
                () -> Svensson.fit(okT,
                        new double[]{0.02, Double.NaN, 0.03, 0.032, 0.035, 0.037}));
        Svensson.Fit fit = Svensson.fit(okT, okR);
        assertThrows(IllegalArgumentException.class, () -> fit.zeroRate(0));
        assertThrows(IllegalArgumentException.class, () -> fit.zeroRate(-1));
    }
}
