package com.quantfinlib.credit;

import com.quantfinlib.rates.YieldCurve;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Second layer of credit pins, complementing {@link CreditTest} and
 * {@link CvaTest}: the flat-hazard ROUND TRIP (spreads generated by one
 * constant hazard bootstrap back to that hazard at every pillar), the
 * exact linear-in-coupon upfront antisymmetry, flat hazard extrapolation
 * beyond the last pillar, CVA linearity, and the gates the first layer
 * did not touch.
 */
class CreditRoundTripTest {

    private static YieldCurve flat3() {
        return YieldCurve.ofZeroRates(new double[]{1, 2, 3, 5, 7, 10},
                new double[]{0.03, 0.03, 0.03, 0.03, 0.03, 0.03});
    }

    // ------------------------------------------------------------ round trip

    @Test
    void spreadsFromOneFlatHazardBootstrapBackToThatHazardEverywhere() {
        // Plant a single flat hazard by bootstrapping ONE pillar, read the
        // par spreads that hazard implies at 1/3/5/7/10y, then bootstrap a
        // fresh multi-pillar curve from those spreads: every recovered
        // pillar hazard must be the planted h, because a flat hazard is
        // the unique piecewise-constant solution repricing all of them.
        YieldCurve discount = flat3();
        CreditCurve base = CreditCurve.bootstrap(new int[]{5},
                new double[]{0.02}, 0.40, discount);
        double h = base.hazard(1.0);

        int[] tenors = {1, 3, 5, 7, 10};
        double[] spreads = new double[tenors.length];
        for (int i = 0; i < tenors.length; i++) {
            spreads[i] = CdsPricer.parSpread(base, discount, tenors[i]);
        }
        CreditCurve rebuilt = CreditCurve.bootstrap(tenors, spreads, 0.40, discount);
        for (double t : new double[]{0.5, 2, 4, 6, 9}) {
            assertEquals(h, rebuilt.hazard(t), 1e-9,
                    "flat-hazard round trip broke at t=" + t);
        }
        // And the survival curves coincide, not just the local hazards.
        assertEquals(base.survivalProbability(8), rebuilt.survivalProbability(8), 1e-9);
    }

    @Test
    void creditTriangleErrorShrinksWithTheSpreadLevel() {
        // The triangle S = h*(1-R) is the flat-curve zeroth-order identity;
        // the discretization/accrual correction is O(spread), so the
        // RELATIVE error at 10bp must be far below the error at 500bp.
        YieldCurve discount = flat3();
        CreditCurve tight = CreditCurve.bootstrap(new int[]{5},
                new double[]{0.001}, 0.40, discount);
        CreditCurve wide = CreditCurve.bootstrap(new int[]{5},
                new double[]{0.05}, 0.40, discount);
        double errTight = Math.abs(tight.hazard(1) - 0.001 / 0.60) / (0.001 / 0.60);
        double errWide = Math.abs(wide.hazard(1) - 0.05 / 0.60) / (0.05 / 0.60);
        assertTrue(errTight < 1e-3, "10bp triangle relative error " + errTight);
        assertTrue(errWide > errTight,
                "500bp error " + errWide + " must exceed 10bp error " + errTight);
    }

    // ----------------------------------------------------------- sign pins

    @Test
    void upfrontIsExactlyAntisymmetricAroundThePar() {
        // upfront(S_c) = protection - S_c * annuity is LINEAR in the
        // coupon, so equal coupon distances above and below par produce
        // upfronts of equal size and opposite sign: a rich coupon means
        // the protection BUYER receives points (negative upfront).
        YieldCurve discount = flat3();
        CreditCurve curve = CreditCurve.bootstrap(new int[]{5},
                new double[]{0.03}, 0.40, discount);
        double par = CdsPricer.parSpread(curve, discount, 5);
        double annuity = CdsPricer.riskyAnnuity(curve, discount, 5);
        double d = 0.01;
        double upCheap = CdsPricer.upfront(curve, discount, par - d, 5);
        double upRich = CdsPricer.upfront(curve, discount, par + d, 5);
        assertEquals(d * annuity, upCheap, 1e-12);
        assertEquals(-d * annuity, upRich, 1e-12);
        assertEquals(-upCheap, upRich, 1e-12, "linear in coupon: exact antisymmetry");
        assertTrue(upRich < 0, "coupon above par: seller pays the buyer points");
        // Premium leg is spread times the annuity by definition.
        assertEquals(0.02 * annuity, CdsPricer.premiumLegPv(curve, discount, 0.02, 5), 1e-15);
    }

    @Test
    void survivalIsStrictlyMonotoneAndExtrapolatesTheLastHazardFlat() {
        YieldCurve discount = flat3();
        CreditCurve curve = CreditCurve.bootstrap(new int[]{1, 3, 5},
                new double[]{0.01, 0.015, 0.02}, 0.40, discount);
        // Strictly decreasing survival on a fine grid.
        double prev = 1.0;
        for (double t = 0.5; t <= 12; t += 0.5) {
            double q = curve.survivalProbability(t);
            assertTrue(q < prev, "survival must fall at t=" + t);
            assertTrue(q > 0);
            prev = q;
        }
        // Beyond the last pillar the hazard is flat, so
        // Q(5+s) = Q(5) * exp(-h_last * s) EXACTLY.
        double hLast = curve.hazard(6.0);
        assertEquals(curve.hazard(5.0), hLast, 0.0, "flat beyond the last pillar");
        assertEquals(curve.survivalProbability(5) * Math.exp(-hLast * 3),
                curve.survivalProbability(8), 1e-15);
    }

    // ---------------------------------------------------------------- gates

    @Test
    void gatesTheFirstLayerMissed() {
        YieldCurve d = flat3();
        assertThrows(IllegalArgumentException.class, () -> CreditCurve.bootstrap(
                new int[]{1}, new double[]{0.01}, -0.1, d));               // negative recovery
        assertThrows(IllegalArgumentException.class, () -> CreditCurve.bootstrap(
                new int[]{0, 1}, new double[]{0.01, 0.01}, 0.4, d));       // zero tenor
        assertThrows(IllegalArgumentException.class, () -> CreditCurve.bootstrap(
                new int[]{1}, new double[]{Double.NaN}, 0.4, d));          // NaN spread
        CreditCurve curve = CreditCurve.bootstrap(new int[]{1},
                new double[]{0.01}, 0.4, d);
        assertThrows(IllegalArgumentException.class, () -> curve.survivalProbability(-1));
        assertThrows(IllegalArgumentException.class, () -> curve.hazard(-0.5));
        assertThrows(IllegalArgumentException.class,
                () -> CdsPricer.parSpread(curve, d, 0));                   // zero maturity
        assertThrows(IllegalArgumentException.class,
                () -> CdsPricer.upfront(curve, d, -0.01, 5));              // negative coupon
    }

    // -------------------------------------------------------------- z-spread

    @Test
    void plantedZSpreadsRoundTripAndPriceFallsInZ() {
        YieldCurve curve = flat3();
        // Plant z, price, solve back: the solver must return the plant.
        for (double z : new double[]{0.005, 0.02, 0.08}) {
            double px = CreditSpreads.priceWithZSpread(100, 0.05, 2, 5, curve, z);
            assertEquals(z, CreditSpreads.zSpread(px, 100, 0.05, 2, 5, curve), 1e-10,
                    "z=" + z + " must round-trip");
        }
        // More z discounts every flow harder: price strictly decreasing.
        double p0 = CreditSpreads.priceWithZSpread(100, 0.05, 2, 5, curve, 0.00);
        double p1 = CreditSpreads.priceWithZSpread(100, 0.05, 2, 5, curve, 0.02);
        double p2 = CreditSpreads.priceWithZSpread(100, 0.05, 2, 5, curve, 0.08);
        assertTrue(p0 > p1 && p1 > p2, "price must fall as z rises");
    }

    // ------------------------------------------------------------------- CVA

    @Test
    void cvaIsLinearInBothExposureAndLgd() {
        // CVA = LGD * sum EE_i * dPD_i * DF_i: doubling the exposure
        // profile or the LGD doubles the number exactly.
        YieldCurve discount = flat3();
        CreditCurve curve = CreditCurve.bootstrap(new int[]{5},
                new double[]{0.02}, 0.40, discount);
        double[] t = {0.5, 1.0, 1.5, 2.0};
        double[] ee = {100, 250, 175, 50};
        double[] ee2 = {200, 500, 350, 100};
        double base = CvaApproximator.cva(ee, t, curve, discount, 0.3);
        assertTrue(base > 0);
        assertEquals(2 * base, CvaApproximator.cva(ee2, t, curve, discount, 0.3), 1e-12);
        assertEquals(2 * base, CvaApproximator.cva(ee, t, curve, discount, 0.6), 1e-12);
    }

    @Test
    void twoPeriodCvaMatchesTheHandSum() {
        // Two buckets, hand-computed: with flat hazard h and flat 3% cc
        // discounting,
        //   CVA = LGD * [ EE1 * (1 - e^{-h/2}) * e^{-0.015}
        //               + EE2 * (e^{-h/2} - e^{-h}) * e^{-0.03} ].
        YieldCurve discount = flat3();
        CreditCurve curve = CreditCurve.bootstrap(new int[]{1},
                new double[]{0.02}, 0.40, discount);
        double h = curve.hazard(0.5);
        double lgd = 0.6;
        double expected = lgd * (100 * (1 - Math.exp(-h * 0.5)) * Math.exp(-0.03 * 0.5)
                + 200 * (Math.exp(-h * 0.5) - Math.exp(-h)) * Math.exp(-0.03 * 1.0));
        assertEquals(expected, CvaApproximator.cva(new double[]{100, 200},
                new double[]{0.5, 1.0}, curve, discount, lgd), 1e-12);
    }
}
